### ISSUE TITLE
bootstrap: packet storm when applying startup-config cause corrupt configuration

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#363]
**State:**
Hardware ports down, system bootstrap

**Problem:**
Takes very long time to start up (see #362) and sometimes the configuration is corrupt.

[startup-config.cfg](https://github.com/kernelkit/infix/files/14760801/startup-config-cfg.txt)

**Theory:**
Ordering issue when activating port and VLAN configuration of bridge.  (PVIDs should be assigned early, interfaces should be taken up last.)

**Comment by troglobit** [comment]
Maybe related to #311?

**Comment by wkz** [comment]
I was never able to reproduce this, even when injecting 10 Gbps of broadcast on the incoming SFP port during the entire boot.

Also, since 080dc6b, the issue of PHYs being up even though the corresponding interface was down has been fixed.

There has also been DDR setup changes to the relevant board, which solved various other issues.
