### ISSUE TITLE
Change toolchain from bleeding-edge to stable

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#383]

**Comment by mattiaswal** [comment]
This has been posponed since the stable toolchain does not work as expected. All container tests failed because:
<pre>
Error: OCI runtime error: unable to start container "d627030632ce814886000ff744ea93897e8f993451f1016ca0e5c3d641f1c6e0": crun: eBPF not supported
</pre>
when change back to bleeding edge everything was fine again.

**Comment by troglobit** [comment]
I propose we close this as "not planned" since we've changed direction, considering the old kernel headers in stable.  We can always create a new issue/task later for the next Buildroot LTS.
